apiVersion: v1
kind: Secret
metadata:
  name: google-credentials
type: Opaque
data:
  GOOGLE_CLIENT_ID: MzIxMjIzMTQ5MDE3LW05NHUzZnRnZGlycmZrcG1pMWx1NDBjZmw5dnV0czZ0LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_CLIENT_SECRET: R09DU1BYLV9qelp4Z0ZHNVFQcnJtN0V2QVZoWVFBQmR2Q04=